#!/usr/bin/env bash

# System
alias shutdown="sudo shutdown now"
alias restart="systemctl reboot"
alias sleep="systemctl hibernate"

# File management
alias cp="cp -v"
alias mv="mv -v"
alias rm="rm -v"

# ls
alias ls="lsd"
alias la="lsd -A"

# cat
alias cat="bat"

# vim
alias vi="nvim"
alias vim="nvim"

# lazygit
alias lg="lazygit"

# reload configs
alias "reload_tmux"="tmux source ~/.config/zsh/.zshrc"
alias "reload_zsh"="exec zsh"

# Directory stack
alias d="dirs -v"
for index ({1..9}) alias "$index"="cd +${index}"; unset index

function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -fq -- "$tmp"
}
alias yazi="y"
